### ISSUE TITLE
Suggest changing U2 from an LDO to a zener diode

### ISSUE THREAD

**Issue by fs94007** [wagiminator/CH32X035-USB-PD-Tester#4]
Suggest changing U2 from an LDO to a zener diode, as the operating current of U1 is less than 5mA, and the LDO seems a bit wasteful. After replacing U2 with a zener diode, the power supply cost decreases from ¥0.48 to ¥0.09.

An example of zener diode:
https://item.szlcsc.com/20275478.html?fromZone=l_c__%2522catalog%2522

**Comment by wagiminator** [comment]
Hi and thanks for the hint. Of course, you can also solve this with a Zener diode, but I prefer to play it safe and stick with the LDO, even if it costs a few cents more.
